= asciibuild - Literate Programming extensions for Asciidoctor
Jon Brisbin <jbrisbin@basho.com>

`asciibuild` is an extension to http://asciidoctor.org[Asciidoctor] that enables https://en.wikipedia.org/wiki/Literate_programming[literate programming] with Asciidoc. It turns the `listing` block into executable code. When you run `asciibuild` on an `.adoc` file that has listing blocks styled with the `[asciibuild]` style, those listing blocks will be executed as they are evaluated by Asciidoctor.

*Think* of `asciibuild` as a simple Notebook. It doesn't require anything but a text editor to create or edit and only command-line tools to run. It allows you put everything related to a process--whether build, test, or orchestration--into source control and let's you use your existing tools and CI/CD workflows.

*Use* `asciibuild` to create full builds, aggregate projects of different kinds that use entirely different build systems, mix multiple languages together in a single `.adoc` file, or create examples and test suites that intermingle the code under test with documentation _about_ the tests.

image:https://travis-ci.org/jbrisbin/asciibuild.svg[link="https://travis-ci.org/jbrisbin/asciibuild/"]

== Sections

This documentation is broken up into the following sections:

include::doc/BUILD.adoc[]

include::doc/USAGE.adoc[]

include::doc/DOCKER.adoc[]
