== Building `asciibuild`

Building `asciibuild` can be done with bundler. The included `Gemfile` contains the necessary configuration to build and install `asciibuild` using a simple `bundle install`.

.Build and Install asciibuild
----
> make install
rm -Rf *.gem vendor *.log metastore_db Dockerfile Gemfile.lock
gem uninstall -x asciibuild
bundle install --no-cache --no-deployment
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using asciidoctor 1.5.4
Using posix-spawn 0.3.11
Using yajl-ruby 1.2.1
Using bundler 1.13.1
Using pygments.rb 0.6.3
Using asciibuild 0.1.0 from source at `.`
Bundle complete! 3 Gemfile dependencies, 6 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
----

This installs the necessary dependencies, as well as the `asciibuild` gem.

=== Building with Docker

If you're using `rbenv` or `rvm` to manage your Ruby environments, then it may not matter to you to have `asciibuild` installed globally. If you want to use `asciibuild` in a Docker container, however, you just need to create a `Dockerfile` with the appropriate `gem install` commands.

.Alpine-based Docker container
[source,Dockerfile]
[concat,file=Dockerfile]
----
FROM alpine
RUN apk add --no-cache bash make build-base ruby ruby-rdoc ruby-irb ruby-bundler ruby-dev py-pip docker
RUN pip install pygments
----

After installing the basics needed by Asciidoctor and Docker, install the necessary gems, as well as `asciibuild` itself.

[concat,file=Dockerfile]
----
RUN mkdir -p /tmp/asciibuild
COPY . /tmp/asciibuild/
WORKDIR /tmp/asciibuild
RUN bundle install
RUN gem build asciibuild.gemspec
RUN gem install ./asciibuild-*.gem -l
RUN rm -Rf /tmp/asciibuild
RUN apk del build-base make ruby-dev
----

Run asciibuild on documents by mounting a volume at `/usr/src`.

[concat,file=Dockerfile]
----
VOLUME /usr/src
WORKDIR /usr/src

ENTRYPOINT ["asciibuild"]
----

Build the Docker image that can run `asciibuild`, expecting documents to be mounted to a volume at path `/usr/src` and, if using the optional Docker support, the Docker daemon socket at `/var/run/docker.sock`.

.Docker build
[asciibuild,bash]
----
docker build -t asciibuild .
----
